In [3]:
import pandas as pd

In [4]:
import os

In [5]:
#importing all the files from the given two excel files
File=pd.read_excel("data.xlsx",sheet_name=None)
File1=pd.read_excel("data_1.xlsx",sheet_name=None)

In [6]:
#itrating through all the sheets in the excel data.xlsx
list1=[]
dataframes=[]
dataframes1=[]
dataframes2=[]
keys = File.keys()
for i in keys:
  list1.append(i)
for i in list1:
    if 'Detail_67' in i:
        dataframes.append(File[i])
    if 'DetailVol_67_' in i:
        dataframes1.append(File[i])
    if 'DetailTemp_67_' in i:
        dataframes2.append(File[i])

In [38]:
# itrating throufh the second excel file dara_1.xlsx
list2=[]
keys1= File1.keys()
for i in keys1:
  list2.append(i)
for i in list2:
    if 'Detail_67' in i:
        dataframes.append(File1[i])
    if 'DetailVol_67_' in i:
        dataframes1.append(File1[i])
    if 'DetailTemp_67_' in i:
        dataframes2.append(File1[i])
join=pd.concat(dataframes)
join.to_csv('detail.csv')
join1=pd.concat(dataframes1)
join1.to_csv('detailVol.csv')
join1=pd.concat(dataframes2)
join1.to_csv('detailTemp.csv')

In [9]:
data=pd.read_csv('detail.csv')

In [10]:
data

,Unnamed: 0,Record Index,Status,JumpTo,Cycle,Step,Cur(mA),Voltage(V),CapaCity(mAh),Energy(mWh),Relative Time(h:min:s.ms),Absolute Time
0,0,1,Rest,1,1,1,0.0,3.5900,0.0,0.0,0:00:00.000,2020-10-10 20:03:39
1,1,2,Rest,1,1,1,0.0,3.5900,0.0,0.0,0:00:01.000,2020-10-10 20:03:40
2,2,3,Rest,1,1,1,0.0,3.5900,0.0,0.0,0:00:02.000,2020-10-10 20:03:41
3,3,4,Rest,1,1,1,0.0,3.5900,0.0,0.0,0:00:03.000,2020-10-10 20:03:42
4,4,5,Rest,1,1,1,0.0,3.5900,0.0,0.0,0:00:04.000,2020-10-10 20:03:43
...,...,...,...,...,...,...,...,...,...,...,...,...
416676,23466,458630,Rest,108,21,83,0.0,3.5856,0.0,0.0,0:09:56.000,2020-10-16 03:25:35
416677,23467,458631,Rest,108,21,83,0.0,3.5853,0.0,0.0,0:09:57.000,2020-10-16 03:25:36
416678,23468,458632,Rest,108,21,83,0.0,3.5853,0.0,0.0,0:09:58.000,2020-10-16 03:25:37
416679,23469,458633,Rest,108,21,83,0.0,3.5856,0.0,0.0,0:09:59.000,2020-10-16 03:25:38
416680,23470,458634,Rest,108,21,83,0.0,3.5856,0.0,0.0,0:10:00.000,2020-10-16 03:25:39

In [19]:
df = pd.DataFrame()
df['Absolute Time'] = pd.date_range(start='2020-10-10',end='2020-10-16',freq='s')
df.to_csv(path_or_buf="detail.csv",index=False)
df = pd.read_csv('detail.csv')
df['Absolute Time'] = pd.to_datetime(df['Absolute Time'])
df = df.resample('1m', on='Absolute Time').first()
df.to_csv(path_or_buf="detailDownsampled.csv",index=False)

In [21]:
df = pd.read_csv('detailVol.csv')
df

,Unnamed: 0,Record ID,Step Name,Relative Time(h:min:s.ms),Realtime,Auxiliary channel TU1 U(V),Gap of Voltage
0,0,1,Rest,0:00:00.000,2020-10-10 20:03:39,-0.0013,0
1,1,2,Rest,0:00:01.000,2020-10-10 20:03:40,-0.0013,0
2,2,3,Rest,0:00:02.000,2020-10-10 20:03:41,-0.0013,0
3,3,4,Rest,0:00:03.000,2020-10-10 20:03:42,-0.0013,0
4,4,5,Rest,0:00:04.000,2020-10-10 20:03:43,-0.0012,0
...,...,...,...,...,...,...,...
416676,23466,458630,Rest,0:09:56.000,2020-10-16 03:25:35,-0.0012,0
416677,23467,458631,Rest,0:09:57.000,2020-10-16 03:25:36,-0.0012,0
416678,23468,458632,Rest,0:09:58.000,2020-10-16 03:25:37,-0.0012,0
416679,23469,458633,Rest,0:09:59.000,2020-10-16 03:25:38,-0.0012,0
416680,23470,458634,Rest,0:10:00.000,2020-10-16 03:25:39,-0.0012,0

In [25]:
df = pd.DataFrame()
df['Realtime'] = pd.date_range(start='2020-10-10',end='2020-10-16',freq='s')
df.to_csv(path_or_buf="detailVol.csv",index=False)
df = pd.read_csv('detailVol.csv')
df['Realtime'] = pd.to_datetime(df['Realtime'])
df = df.resample('1m', on='Realtime').first()
df.to_csv(path_or_buf="detailVolDownsampled.csv",index=False)

In [27]:
df = pd.read_csv('detailTemp.csv')
df

,Unnamed: 0,Record ID,Step Name,Relative Time(h:min:s.ms),Realtime,Auxiliary channel TU1 T(Â°C),Gap of Temperature
0,0,1,Rest,0:00:00.000,2020-10-10 20:03:39,27.7,0
1,1,2,Rest,0:00:01.000,2020-10-10 20:03:40,27.7,0
2,2,3,Rest,0:00:02.000,2020-10-10 20:03:41,27.7,0
3,3,4,Rest,0:00:03.000,2020-10-10 20:03:42,27.7,0
4,4,5,Rest,0:00:04.000,2020-10-10 20:03:43,27.7,0
...,...,...,...,...,...,...,...
196600,65530,196601,CCCV_DChg,0:04:05.000,2020-10-13 02:39:27,28.3,0
196601,65531,196602,CCCV_DChg,0:04:06.000,2020-10-13 02:39:28,28.3,0
196602,65532,196603,CCCV_DChg,0:04:07.000,2020-10-13 02:39:29,28.3,0
196603,65533,196604,CCCV_DChg,0:04:08.000,2020-10-13 02:39:30,28.3,0
196604,65534,196605,CCCV_DChg,0:04:09.000,2020-10-13 02:39:31,28.3,0

In [29]:
df = pd.DataFrame()
df['Realtime'] = pd.date_range(start='2020-10-10',end='2020-10-16',freq='s')
df.to_csv(path_or_buf="detailTemp.csv",index=False)
df = pd.read_csv('detailTemp.csv')
df['Realtime'] = pd.to_datetime(df['Realtime'])
df = df.resample('1m', on='Realtime').first()
df.to_csv(path_or_buf="detailTempDownsampled.csv",index=False)

In [30]:
data.shape

(416681, 12)

In [31]:
data.head(3)

,Unnamed: 0,Record Index,Status,JumpTo,Cycle,Step,Cur(mA),Voltage(V),CapaCity(mAh),Energy(mWh),Relative Time(h:min:s.ms),Absolute Time
0,0,1,Rest,1,1,1,0.0,3.59,0.0,0.0,0:00:00.000,2020-10-10 20:03:39
1,1,2,Rest,1,1,1,0.0,3.59,0.0,0.0,0:00:01.000,2020-10-10 20:03:40
2,2,3,Rest,1,1,1,0.0,3.59,0.0,0.0,0:00:02.000,2020-10-10 20:03:41